Fix aggregateByKey python binding
tuplex/tuplex pull request #16
Opened 2021-07-26 18:58 UTC by rahulyesantharao

The python binding for `aggregateByKey` (in `dataset.py`) currently crashes due to the deprecated function `get_lambda_source` - update to the new function `get_udf_source`.

2021-07-27 14:36 UTC, ms705 approved these changes
LGTM; let's merge if @LeonhardFS approves.

2021-07-29 01:04 UTC, LeonhardFS commented
Great, to get this fixed - yet I feel this PR could benefit from adding a (python) test targeting specifically aggregateByKey to the code base, so we will be alerted in the future and won't forget the code accordingly.

Also, is get_lambda_source still a valid function? If it's deprecated, we probably should remove it.

2021-07-29 01:05 UTC, LeonhardFS requested changes
pls add a python test for aggregateByKey & check whether get_lambda-source still exists somewhere in the code base.

2021-07-29 01:06 UTC, LeonhardFS commented
Another thing to maybe improve here is to not use a catch-all `try:.... except:...` block which basically lead to silent failure, but rather test for a specific CodeExtraction Exception.

2021-07-30 20:40 UTC, rahulyesantharao commented
`get_lambda_source` is in [interactive_shell.py](https://github.com/tuplex/tuplex/blob/master/tuplex/python/tuplex/utils/interactive_shell.py#L90) and is used in [reflection.py](https://github.com/tuplex/tuplex/blob/master/tuplex/python/tuplex/utils/reflection.py#L179)

2021-08-04 14:07 UTC, LeonhardFS commented
superseded by #19 , closed for now.

2021-08-04 14:07 UTC, closed without merging